name: Health checkout

on:
  schedule:
    - cron: "15 12 1-31 1-12 SUN-SAT"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Run health Check
        run: echo 'Running health check'
      - uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-a.onrender.com/health