name: Deployment pipeline

env:
  ARRAY_COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
  SKIPPABLE: ${{ contains( join( toJson(github.event.commits.*.message) ), '#skip') }}

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Run normal CI
        run: echo 'Running normal CI'
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      
      - name: e2e tests
        uses: cypress-io/github-action@c5724eda82337bcff977ce14509f47052c12e04c
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      
      - if: ${{ github.event_name == 'push' && env.SKIPPABLE == 'false' }}
        uses: johnbeynon/render-deploy-action@a0588f9aca995a15d69a72cb2bfbf37c12e5b540
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-success: true
        
      - name: Success Notify
        if: ${{ success() }}
        uses: rjstone/discord-webhook-notify@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          text: |
            A new version of Pokedex was deployed

      - name: Failed Notify
        if: ${{ failure() }}
        uses: rjstone/discord-webhook-notify@v2
        with:
          severity: error
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          text: |
            Render deployment failed


  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:

      - name: Run versioning CI
        run: echo 'Running versioning CI'
      - uses: actions/checkout@v4

      - name: Bump version and push tag
        if: ${{ env.SKIPPABLE == 'false' }}
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX: v
          DEFAULT_BUMP: patch